spring:
  datasource:
    url: # jdbc:mysql://ip:3306/DB_NAME?autoReconnect=true
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    config:
      classpath: logback.xml

  data:
    redis:
      host:
      port: 6379

  server:
    port: 3000